name: Java CI

on:
  pull_request:
  push:
    branches:    
      - main
  schedule:
    - cron: 0 6 * * *

jobs:

  test:
    name: "Build Jar"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        ./gradlew clean jar
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: build/libs
    - name: Run tests and produce report with Gradle
      run: |
        ./gradlew --stacktrace clean check
    - uses: actions/upload-artifact@master
      with:
        name: build reports
        path: build/reports

  pittest:
    name: "Run Pit Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Pittest
      run: |
        ./gradlew pitest
    - uses: actions/upload-artifact@master
      with:
        name: pittest
        path: build
