name: Java CI

on:
  push:
  schedule:
    - cron: 0 6 * * *

jobs:
  test:
    name: "Test on ubuntu latest with JDK 1.8"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew check
